"""
FastAPI application entrypoint.

Run: uvicorn app.main:app --reload --port 8000
Docs: http://localhost:8000/docs (auto-generated by FastAPI)
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.routes import router

app = FastAPI(title="OrbitalAid API", version="0.1.0")

# Allows local dev (localhost:3000) and the deployed Vercel frontend.
# allow_origin_regex covers Vercel's per-deployment preview URLs too
# (e.g. orbital-aid-gngh-<hash>-rahuls-projects....vercel.app), not just
# the main production domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_origin_regex=r"https://orbital-aid.*\.vercel\.app",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router)


@app.get("/")
def root():
    return {"status": "ok", "service": "OrbitalAid API"}