"""
FastAPI application entrypoint.

Run: uvicorn app.main:app --reload --port 8000
Docs: http://localhost:8000/docs (auto-generated by FastAPI)
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.routes import router

app = FastAPI(title="OrbitalAid API", version="0.1.0")

# CORS: Next.js dev server runs on a different port than this API, so the
# browser blocks requests by default without this. Update allow_origins
# when deploying somewhere other than localhost.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router)


@app.get("/")
def root():
    return {"status": "ok", "service": "OrbitalAid API"}